FROM python:3.10
# Contains relevant basics for Python, like GCC and similar by default
LABEL maintainer="ensembl-variation@ebi.ac.uk"

COPY ./requirements.txt /app/requirements.txt
COPY ./requirements-dev.txt /app/requirements-dev.txt
COPY ./setup.py /app/setup.py
COPY ./LICENSE /app/LICENSE

RUN pip3 install -r /app/requirements-dev.txt -e /app/

ENV PYTHONPATH=\$PYTHONPATH:/app

EXPOSE 8000

WORKDIR /app

ENV WORKER_COUNT=1
CMD uvicorn --workers $WORKER_COUNT --host=0.0.0.0 graphql_service.server:APP
